/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;
import java.util.Scanner;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class App {

    // TODO: Add a calculation here
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       //TODO Test todo comment
    }
}
